language: python

python:
    - "3.6"

services:
    - postgresql

install:
    - pip install -r requirements.txt

before_script:
    - psql -c "create database stackoverflow;" -U postgres


script:
    - pytest --cov=StackOverflow-lite

after_success:
    - coveralls
